name       : mda-lv2
version    : 1.2.2
release    : 2
source     :
    - http://download.drobilla.net/mda-lv2-1.2.2.tar.bz2 : a476c31ed9f8b009ebacc32a02d06ba9584c0d0d03f03dd62b1354d10a030442
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : MDA-LV2 is an LV2 port of the MDA plugins by Paul Kellett.
description: |
    MDA-LV2 is an LV2 port of the MDA plugins by Paul Kellett. It contains 36 high-quality plugins for a variety of tasks.
builddeps  :
    - pkgconfig(lv2)
setup      : |
    ./waf configure --prefix=/usr --libdir=%libdir%
build      : |
    ./waf
install    : |
    ./waf install --destdir="%installroot%"
