name       : mda-lv2
version    : 1.2.6
release    : 4
source     :
    - https://download.drobilla.net/mda-lv2-1.2.6.tar.bz2 : cd66117024ae049cf3aca83f9e904a70277224e23a969f72a9c5d010a49857db
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : MDA-LV2 is an LV2 port of the MDA plugins by Paul Kellett.
description: |
    MDA-LV2 is an LV2 port of the MDA plugins by Paul Kellett. It contains 36 high-quality plugins for a variety of tasks.
builddeps  :
    - pkgconfig(lv2)
setup      : |
    %waf_configure --libdir=%libdir%
build      : |
    %waf_build
install    : |
    %waf_install
